trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: echo K8S Terraform Azure!
    displayName: "Run a one-line script"
  - task: DownloadSecureFile@1
    name: publickey
    inputs:
      secureFile: "azure_rsa.pub"

  - task: TerraformCLI@0
    inputs:
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/projects/microservices/01-currency-exchange-microservice-basic/configuration/iaac/azure/'
      backendType: 'azurerm'
      backendServiceArm: 'gvr-azure-rm service-conn'
      ensureBackend: true
      backendAzureRmResourceGroupName: 'terraform-backend-rg'
      backendAzureRmResourceGroupLocation: 'eastus'
      backendAzureRmStorageAccountName: 'storageacctrangaxyz'
      backendAzureRmContainerName: 'storageacctrangacontainer'
      backendAzureRmKey: 'kubernetes-dev.tfstate'

  - task: TerraformCLI@0
    inputs:
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/projects/microservices/01-currency-exchange-microservice-basic/configuration/iaac/azure/'
      environmentServiceName: 'gvr-azure-rm service-conn'
      commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'