trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo K8s Terrafomr Azure!
  displayName: 'Run a one-line script'
  
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure-rsa.pub'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/projects/microservices/01-currency-exchange-microservice-basic/configuration/iaac/azure/'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    backendType: 'azurerm'
    backendServiceArm: 'gvr-azure-rm service-conn'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-backend-rg'
    backendAzureRmResourceGroupLocation: 'eastus'
    backendAzureRmStorageAccountName: 'gvrstorageterraform1'
    backendAzureRmContainerName: 'gvrstoragecontainer'
    backendAzureRmKey: 'kubernetes-dev.tfstate'

